import { QuestionConfig } from '@/types';

export const QUESTIONS: QuestionConfig[] = [
  {
    key: 'sleepHours',
    label: 'Sleep Quality',
    description: 'How well did you sleep last night?',
    lowLabel: 'So badddd',
    highLabel: 'Like a baby',
    icon: '😴',
  },
  {
    key: 'exerciseFrequency',
    label: 'Love of late-night snacks',
    description: 'How hard did you hit the late-night snacks this week?',
    lowLabel: 'Didn\'t snack (weirdo)',
    highLabel: 'fridge is empty now',
    icon: '🌮',
  },
  {
    key: 'stressLevel',
    label: 'Current Stress Level',
    description: 'Right now, how stressed are you feeling from MAs/Assignments?',
    lowLabel: 'Totally Chill',
    highLabel: 'Completely stressed out',
    icon: '😰',
  },
  {
    key: 'screenTime',
    label: 'Meme Intake',
    description: 'How much time did you spend looking at memes/reels (so far) today?',
    lowLabel: 'Zero memes',
    highLabel: 'It\'s all I did',
    icon: '😂',
  },
  {
    key: 'socialActivity',
    label: 'Extroversion',
    description: 'Generally, how much do you enjoy being around lots of people?',
    lowLabel: 'Really Introverted',
    highLabel: 'Really Extroverted',
    icon: '👥',
  },
  {
    key: 'productivity',
    label: 'Procrastination Today',
    description: 'How much did you procrastinate today?',
    lowLabel: 'Got everything done',
    highLabel: 'I\'ll do it tomorrow',
    icon: '🦥',
  },
  {
    key: 'moodRating',
    label: 'Current Mood',
    description: 'How are you feeling right now?',
    lowLabel: 'Really down',
    highLabel: 'Fantastic',
    icon: '🎭',
  },
  {
    key: 'caffeineIntake',
    label: 'Caffeine Today',
    description: 'How much coffee/tea/energy drinks have you had today?',
    lowLabel: 'None',
    highLabel: 'Lost count',
    icon: '☕',
  },
  {
    key: 'petAffinity',
    label: 'Dog vs Cat',
    description: 'Are you more of a dog person or cat person?',
    lowLabel: 'Totally cats',
    highLabel: 'Totally dogs',
    icon: '🐾',
  },
  {
    key: 'musicVolume',
    label: 'Music Volume',
    description: 'When you listen to music, how loud is it usually?',
    lowLabel: 'Barely audible',
    highLabel: 'Max volume',
    icon: '🎧',
  },
  {
    key: 'chaosEnergy',
    label: 'Risk Taking',
    description: 'How comfortable are you taking risks?',
    lowLabel: 'I play it safe',
    highLabel: 'Gamble it all',
    icon: '🎲',
  },
  {
    key: 'pizzaOpinion',
    label: 'Pineapple Pizza',
    description: 'Pineapple on pizza?',
    lowLabel: 'Never.',
    highLabel: 'Yes, it\'s amazing!',
    icon: '🍕',
  },
  {
    key: 'optimism',
    label: 'Optimism',
    description: 'When something bad happens, do you expect things to get better?',
    lowLabel: 'Never :(',
    highLabel: 'Of course!',
    icon: '🌈',
  },
  {
    key: 'decision',
    label: 'Decision Style',
    description: 'When making decisions, do you go with your gut or think it through?',
    lowLabel: 'Pure logic',
    highLabel: 'Pure intuition',
    icon: '🧠',
  },
  {
    key: 'homeworkStress',
    label: 'Homework Load',
    description: 'How heavy does your homework load feel this week?',
    lowLabel: 'Super light',
    highLabel: 'Drowning in it',
    icon: '📚',
  },
  {
    key: 'socialBattery',
    label: 'Social Battery',
    description: 'After a full day of classes, how drained is your social battery?',
    lowLabel: 'Still full',
    highLabel: 'Completely empty',
    icon: '🔋',
  },
];

export const QUESTION_LABELS: Record<string, string> = {
  sleepHours: 'Sleep Quality',
  exerciseFrequency: 'Night Snack Lovin',
  stressLevel: 'Stress Level',
  screenTime: 'Meme Intake',
  socialActivity: 'Extroversion',
  productivity: 'Procrastination',
  moodRating: 'Current Mood',
  caffeineIntake: 'Caffeine',
  petAffinity: 'Dog Over Cat',
  musicVolume: 'Average Music Volume',
  chaosEnergy: 'Risk Taking',
  pizzaOpinion: 'Pineapple Pizza',
  optimism: 'Optimism',
  decision: 'Intuition Over Logic',
  homeworkStress: 'Homework Load',
  socialBattery: 'Social Battery',
};
